//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int ProId { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Size { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ProductList ProductList { get; set; }
        public virtual UserD UserD { get; set; }
    }
}
