//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public int AddressId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string AddressL { get; set; }
        public string PhoneN { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
