//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public int QueryId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Query1 { get; set; }
    }
}
